# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bodhi/KOK_ENGINE/KOK_ENGINE/KOK_ENGINE_0_1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bodhi/KOK_ENGINE/KOK_ENGINE/KOK_ENGINE_0_1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bodhi/KOK_ENGINE/KOK_ENGINE/KOK_ENGINE_0_1/CMakeFiles /home/bodhi/KOK_ENGINE/KOK_ENGINE/KOK_ENGINE_0_1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bodhi/KOK_ENGINE/KOK_ENGINE/KOK_ENGINE_0_1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test2

# Build rule for target.
test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test2
.PHONY : test2

# fast build rule for target.
test2/fast:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/build
.PHONY : test2/fast

#=============================================================================
# Target rules for targets named KOKg

# Build rule for target.
KOKg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KOKg
.PHONY : KOKg

# fast build rule for target.
KOKg/fast:
	$(MAKE) -f KOK_GRAPHICS/CMakeFiles/KOKg.dir/build.make KOK_GRAPHICS/CMakeFiles/KOKg.dir/build
.PHONY : KOKg/fast

#=============================================================================
# Target rules for targets named KOKc

# Build rule for target.
KOKc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KOKc
.PHONY : KOKc

# fast build rule for target.
KOKc/fast:
	$(MAKE) -f KOK_CORE/CMakeFiles/KOKc.dir/build.make KOK_CORE/CMakeFiles/KOKc.dir/build
.PHONY : KOKc/fast

#=============================================================================
# Target rules for targets named KOKa

# Build rule for target.
KOKa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KOKa
.PHONY : KOKa

# fast build rule for target.
KOKa/fast:
	$(MAKE) -f KOK_ANGEL/CMakeFiles/KOKa.dir/build.make KOK_ANGEL/CMakeFiles/KOKa.dir/build
.PHONY : KOKa/fast

#=============================================================================
# Target rules for targets named KOKp

# Build rule for target.
KOKp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KOKp
.PHONY : KOKp

# fast build rule for target.
KOKp/fast:
	$(MAKE) -f KOK_PHYSICS/CMakeFiles/KOKp.dir/build.make KOK_PHYSICS/CMakeFiles/KOKp.dir/build
.PHONY : KOKp/fast

KOK_EXTENDS/src/KOK_EXT_CharacterBasic.o: KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.o

.PHONY : KOK_EXTENDS/src/KOK_EXT_CharacterBasic.o

# target to build an object file
KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.o:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.o
.PHONY : KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.o

KOK_EXTENDS/src/KOK_EXT_CharacterBasic.i: KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.i

.PHONY : KOK_EXTENDS/src/KOK_EXT_CharacterBasic.i

# target to preprocess a source file
KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.i:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.i
.PHONY : KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.i

KOK_EXTENDS/src/KOK_EXT_CharacterBasic.s: KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.s

.PHONY : KOK_EXTENDS/src/KOK_EXT_CharacterBasic.s

# target to generate assembly for a file
KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.s:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.s
.PHONY : KOK_EXTENDS/src/KOK_EXT_CharacterBasic.cpp.s

tests/gui.o: tests/gui.cpp.o

.PHONY : tests/gui.o

# target to build an object file
tests/gui.cpp.o:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/tests/gui.cpp.o
.PHONY : tests/gui.cpp.o

tests/gui.i: tests/gui.cpp.i

.PHONY : tests/gui.i

# target to preprocess a source file
tests/gui.cpp.i:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/tests/gui.cpp.i
.PHONY : tests/gui.cpp.i

tests/gui.s: tests/gui.cpp.s

.PHONY : tests/gui.s

# target to generate assembly for a file
tests/gui.cpp.s:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/tests/gui.cpp.s
.PHONY : tests/gui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... test2"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... KOKg"
	@echo "... KOKc"
	@echo "... KOKa"
	@echo "... KOKp"
	@echo "... KOK_EXTENDS/src/KOK_EXT_CharacterBasic.o"
	@echo "... KOK_EXTENDS/src/KOK_EXT_CharacterBasic.i"
	@echo "... KOK_EXTENDS/src/KOK_EXT_CharacterBasic.s"
	@echo "... tests/gui.o"
	@echo "... tests/gui.i"
	@echo "... tests/gui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

